package com.github.wohaopa.MyCTMLib.render.context;

public enum RenderMethod {
    RENDER_BLOCK_BY_RENDER_TYPE,
    RENDER_STANDARD_BLOCK,
    RENDER_STANDARD_BLOCK_WITH_AO,
    RENDER_BLOCK_AS_ITEM,
    RENDER_ENTITIES,
    RENDER_ENTITY_STATIC,
    DO_RENDER,
    RENDER_ITEM,
    RENDER_ITEM_IN_FIRST_PERSON,
    RENDER_FACE_Y_POS,
    RENDER_FACE_Y_NEG,
    RENDER_FACE_X_POS,
    RENDER_FACE_X_NEG,
    RENDER_FACE_Z_POS,
    RENDER_FACE_Z_NEG
}
